=== DeepuBhasin/Personalprojects/8. XML/DTD Project/transactions.dtd
<!ELEMENT transactions (shop*,author)>
<!ATTLIST shop giftShop CDATA "0">
<!ELEMENT shop (date)*>
<!ATTLIST date transaction_date CDATA "01/11/2019">
<!ELEMENT date (transactionDetails)*>
<!ELEMENT transactionDetails (transaction,customer)*>
<!ELEMENT transaction (transaction_id,value)>
<!ELEMENT transaction_id (#PCDATA)*>
<!ELEMENT value (#PCDATA)*>
<!ATTLIST value currency CDATA "gbp">
<!ELEMENT customer (prefix,lastName,givenName,addressID,customerID)>
<!ELEMENT prefix (#PCDATA)*>
<!ELEMENT lastName (#PCDATA)*>
<!ELEMENT givenName (#PCDATA)*>
<!ELEMENT addressID (#PCDATA)*>
<!ELEMENT customerID (#PCDATA)*>
<!ELEMENT author (#PCDATA)*>
<!ENTITY firstname "mahfuzur">
<!ENTITY lastname "1000">

=== DeepuBhasin/Personalprojects/8. XML/DTD Project/output.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE transactions SYSTEM "transactions.dtd">
<transactions>
	<shop giftShop="1">
	  <date transaction_date="01/11/2019">
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"xiFZUFOv8J8zKqyU"</transaction_id>
		 		<value currency="gbp">19.76</value>
		 	</transaction>
			<customer>
			 	<prefix>"Miss"</prefix>
			 	<lastName>"Witherspoon"</lastName>
			 	<givenName>"Wisdom"</givenName>
			 	<addressID>"306679"</addressID>
			 	<customerID>"BQ0JG15U"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"7Yog0IVnlVbOGIQX"</transaction_id>
		 		<value currency="gbp">54.12</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Bellamy"</lastName>
			 	<givenName>"Sawyer"</givenName>
			 	<addressID>"792091"</addressID>
			 	<customerID>"4FI1TAJW"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"6vtTiqxOcrZn6DEU"</transaction_id>
		 		<value currency="gbp">68.06</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mrs"</prefix>
			 	<lastName>"MacConnell"</lastName>
			 	<givenName>"Selina"</givenName>
			 	<addressID>"62588"</addressID>
			 	<customerID>"EO1KDAFV"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"SgjnoLMH9VEVixHs"</transaction_id>
		 		<value currency="gbp">57.94</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mrs"</prefix>
			 	<lastName>"Wilton"</lastName>
			 	<givenName>"Starla"</givenName>
			 	<addressID>"483243"</addressID>
			 	<customerID>"OGUQVY70"</customerID>
		 	</customer>
		 </transactionDetails>
		</date>
		<date transaction_date="02/11/2019">
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"1Lng8B0uDphSQhu4"</transaction_id>
		 		<value currency="gbp">0.89</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mrs"</prefix>
			 	<lastName>"Dhuibh"</lastName>
			 	<givenName>"Minta"</givenName>
			 	<addressID>"331249"</addressID>
			 	<customerID>"QQASCC8J"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"FdHLlG1RAcnSJf4p"</transaction_id>
		 		<value currency="gbp">43.2</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Simpson"</lastName>
			 	<givenName>"Darcy"</givenName>
			 	<addressID>"546250"</addressID>
			 	<customerID>"9J1R7LKH"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"McnBd7VFUUqkBszp"</transaction_id>
		 		<value currency="gbp">80.21</value>
		 	</transaction>
			<customer>
			 	<prefix>"Ms"</prefix>
			 	<lastName>"Stringer"</lastName>
			 	<givenName>"Coretta"</givenName>
			 	<addressID>"64056"</addressID>
			 	<customerID>"Z0A07AOV"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"IX9UspYJgYTYwtbI"</transaction_id>
		 		<value currency="gbp">13.84</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mrs"</prefix>
			 	<lastName>"Tobias"</lastName>
			 	<givenName>"Talia"</givenName>
			 	<addressID>"790366"</addressID>
			 	<customerID>"A25S3UU6"</customerID>
		 	</customer>
		 </transactionDetails>
		</date>
		<date transaction_date="03/11/2019">
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"52m2IVzGHpcS2a2N"</transaction_id>
		 		<value currency="gbp">19.78</value>
		 	</transaction>
			<customer>
			 	<prefix>"Dr"</prefix>
			 	<lastName>"Foss"</lastName>
			 	<givenName>"Kaycee"</givenName>
			 	<addressID>"513089"</addressID>
			 	<customerID>"2YOK85QF"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"9y56RANfMNM9KTkK"</transaction_id>
		 		<value currency="gbp">35.33</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Lyon"</lastName>
			 	<givenName>"Laz"</givenName>
			 	<addressID>"259820"</addressID>
			 	<customerID>"NFP1RIH5"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"MPRDuvVBW3EYul6K"</transaction_id>
		 		<value currency="gbp">34.12</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Scriven"</lastName>
			 	<givenName>"Gib"</givenName>
			 	<addressID>"86916"</addressID>
			 	<customerID>"TUUSA0SI"</customerID>
		 	</customer>
		 </transactionDetails>
		</date>		
	</shop>
	<shop giftShop="2">
		<date transaction_date="01/11/2019">
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"nbRHpxXbUzlw86Yu"</transaction_id>
		 		<value currency="gbp">17.14</value>
		 	</transaction>
			<customer>
			 	<prefix>"Dr"</prefix>
			 	<lastName>"Brownlow"</lastName>
			 	<givenName>"Osmond"</givenName>
			 	<addressID>"279126"</addressID>
			 	<customerID>"84WIFUAH"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"xNcmC90pdXYcdUNF"</transaction_id>
		 		<value currency="gbp">72.96</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Boyle"</lastName>
			 	<givenName>"Cohen"</givenName>
			 	<addressID>"92016"</addressID>
			 	<customerID>"DOWK75O4"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"2lZ75q0FrSpcREjs"</transaction_id>
		 		<value currency="gbp">49.49</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mrs"</prefix>
			 	<lastName>"Bateson"</lastName>
			 	<givenName>"Karissa"</givenName>
			 	<addressID>"468126"</addressID>
			 	<customerID>"FDCXOH0M"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"L72fYINuLfbm61yr"</transaction_id>
		 		<value currency="gbp">57.26</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Hopper"</lastName>
			 	<givenName>"Tadhg"</givenName>
			 	<addressID>"787046"</addressID>
			 	<customerID>"CMNY0DKI"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"f2bXNaWqlGR8k2kh"</transaction_id>
		 		<value currency="gbp">13.94</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Alfredson"</lastName>
			 	<givenName>"Malakai"</givenName>
			 	<addressID>"704817"</addressID>
			 	<customerID>"IE6T80M6"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"1ygOIpJ6Tf2HB72e"</transaction_id>
		 		<value currency="gbp">57.43</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Trask"</lastName>
			 	<givenName>"Fearchar"</givenName>
			 	<addressID>"13287"</addressID>
			 	<customerID>"31F9PCQD"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"4oZAWTFBGOuNtjm6"</transaction_id>
		 		<value currency="gbp">56.13</value>
		 	</transaction>
			<customer>
			 	<prefix>"Ms"</prefix>
			 	<lastName>"Britton"</lastName>
			 	<givenName>"Estella"</givenName>
			 	<addressID>"946382"</addressID>
			 	<customerID>"KKDLTC4B"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"oTfh5Dg0ACCGG0SH"</transaction_id>
		 		<value currency="gbp">8.59</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Shaughnessy"</lastName>
			 	<givenName>"Paddy"</givenName>
			 	<addressID>"303203"</addressID>
			 	<customerID>"BA1LBL11"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"jybwh5EroaL4FfJs"</transaction_id>
		 		<value currency="gbp">75.92</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Harley"</lastName>
			 	<givenName>"Monroe"</givenName>
			 	<addressID>"882651"</addressID>
			 	<customerID>"0V1XOKLR"</customerID>
		 	</customer>
		 </transactionDetails>
		</date>
		<date transaction_date="02/11/2019">
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"eb7zMnKoshn3NZBi"</transaction_id>
		 		<value currency="gbp">12.75</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Russell"</lastName>
			 	<givenName>"Caiden"</givenName>
			 	<addressID>"528598"</addressID>
			 	<customerID>"6AQU1HBA"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"QqLta5wpcNpnjmgU"</transaction_id>
		 		<value currency="gbp">17</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Strickland"</lastName>
			 	<givenName>"Beverly"</givenName>
			 	<addressID>"158426"</addressID>
			 	<customerID>"XQW4T04U"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"jOuIoNvwJbvPOk8o"</transaction_id>
		 		<value currency="gbp">41.75</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mr "</prefix>
			 	<lastName>"Ott"</lastName>
			 	<givenName>"Domhnall"</givenName>
			 	<addressID>"649633"</addressID>
			 	<customerID>"7RI52S4J"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"9MxQ2jmzMLFY1Xae"</transaction_id>
		 		<value currency="gbp">1.33</value>
		 	</transaction>
			<customer>
			 	<prefix>"Mrs"</prefix>
			 	<lastName>"Greer"</lastName>
			 	<givenName>"Finola"</givenName>
			 	<addressID>"51550"</addressID>
			 	<customerID>"ZIT8QPN5"</customerID>
		 	</customer>
		 </transactionDetails>
		 <transactionDetails>
		 	<transaction>
		 		<transaction_id>"LDssnuvX8yr9U8W0"</transaction_id>
		 		<value currency="gbp">9.51</value>
		 	</transaction>
			<customer>
