=== DeepuBhasin/Personalprojects/7. XML/robertogarciaga-attachments/xml_schema.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT data (electricalMedicalRecord,insuranceComapny,physician)>
<!ATTLIST data
  xmlns CDATA #FIXED ''>

<!ELEMENT electricalMedicalRecord (patientInfromation)+>
<!ATTLIST electricalMedicalRecord
  xmlns CDATA #FIXED ''>

<!ELEMENT insuranceComapny (company)+>
<!ATTLIST insuranceComapny
  xmlns CDATA #FIXED ''>

<!ELEMENT physician (physicianInfromation)+>
<!ATTLIST physician
  xmlns CDATA #FIXED ''>

<!ELEMENT patientInfromation (personalInfromation,MedicalInfromation)>
<!ATTLIST patientInfromation
  xmlns CDATA #FIXED ''>

<!ELEMENT company (companyId,companyName,location,revenue,employees,
                   customerDetails)>
<!ATTLIST company
  xmlns CDATA #FIXED ''>

<!ELEMENT physicianInfromation (pysiciansId,name,specialist,address,
                                about,patiendDetails)>
<!ATTLIST physicianInfromation
  xmlns CDATA #FIXED ''>

<!ELEMENT personalInfromation (userId,FirstName,lastName,gender,address,
                               age,weight)>
<!ATTLIST personalInfromation
  xmlns CDATA #FIXED ''>

<!ELEMENT MedicalInfromation (TreatmentOf,subCategory,medication,
                              allergies,immunizationStatus,
                              medicalHistory,billingInfromation)>
<!ATTLIST MedicalInfromation
  xmlns CDATA #FIXED ''>

<!ELEMENT companyId (#PCDATA)>
<!ATTLIST companyId
  xmlns CDATA #FIXED ''>

<!ELEMENT companyName (#PCDATA)>
<!ATTLIST companyName
  xmlns CDATA #FIXED ''>

<!ELEMENT location (#PCDATA)>
<!ATTLIST location
  xmlns CDATA #FIXED ''>

<!ELEMENT revenue (#PCDATA)>
<!ATTLIST revenue
  xmlns CDATA #FIXED ''>

<!ELEMENT employees (#PCDATA)>
<!ATTLIST employees
  xmlns CDATA #FIXED ''>

<!ELEMENT customerDetails (customerId,totalBalance,timePeriod,
                           transactions)>
<!ATTLIST customerDetails
  xmlns CDATA #FIXED ''>

<!ELEMENT pysiciansId (#PCDATA)>
<!ATTLIST pysiciansId
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT specialist (#PCDATA)>
<!ATTLIST specialist
  xmlns CDATA #FIXED ''>

<!ELEMENT about (#PCDATA)>
<!ATTLIST about
  xmlns CDATA #FIXED ''>

<!ELEMENT patiendDetails (patiendId,checkHistory)>
<!ATTLIST patiendDetails
  xmlns CDATA #FIXED ''>

<!ELEMENT userId (#PCDATA)>
<!ATTLIST userId
  xmlns CDATA #FIXED ''>

<!ELEMENT FirstName (#PCDATA)>
<!ATTLIST FirstName
  xmlns CDATA #FIXED ''>

<!ELEMENT lastName (#PCDATA)>
<!ATTLIST lastName
  xmlns CDATA #FIXED ''>

<!ELEMENT gender (#PCDATA)>
<!ATTLIST gender
  xmlns CDATA #FIXED ''>

<!ELEMENT age (#PCDATA)>
<!ATTLIST age
  xmlns CDATA #FIXED ''>

<!ELEMENT weight (#PCDATA)>
<!ATTLIST weight
  xmlns CDATA #FIXED ''>

<!ELEMENT TreatmentOf (#PCDATA)>
<!ATTLIST TreatmentOf
  xmlns CDATA #FIXED ''>

<!ELEMENT subCategory (#PCDATA)>
<!ATTLIST subCategory
  xmlns CDATA #FIXED ''>

<!ELEMENT medication (#PCDATA)>
<!ATTLIST medication
  xmlns CDATA #FIXED ''>

<!ELEMENT allergies (#PCDATA)>
<!ATTLIST allergies
  xmlns CDATA #FIXED ''>

<!ELEMENT immunizationStatus (#PCDATA)>
<!ATTLIST immunizationStatus
  xmlns CDATA #FIXED ''>

<!ELEMENT medicalHistory (consultations,surgeries,
                          LaborarotyTestResults)>
<!ATTLIST medicalHistory
  xmlns CDATA #FIXED ''>

<!ELEMENT billingInfromation (Bank,AccountId)>
<!ATTLIST billingInfromation
  xmlns CDATA #FIXED ''>

<!ELEMENT customerId (#PCDATA)>
<!ATTLIST customerId
  xmlns CDATA #FIXED ''
  userId NMTOKEN #REQUIRED>

<!ELEMENT totalBalance (#PCDATA)>
<!ATTLIST totalBalance
  xmlns CDATA #FIXED ''
  currency NMTOKEN #REQUIRED>

<!ELEMENT timePeriod (#PCDATA)>
<!ATTLIST timePeriod
  xmlns CDATA #FIXED ''>

<!ELEMENT transactions (transaction)+>
<!ATTLIST transactions
  xmlns CDATA #FIXED ''>

<!ELEMENT patiendId (#PCDATA)>
<!ATTLIST patiendId
  xmlns CDATA #FIXED ''
  userId NMTOKEN #REQUIRED>

<!ELEMENT checkHistory (check)+>
<!ATTLIST checkHistory
  xmlns CDATA #FIXED ''>

<!ELEMENT consultations (#PCDATA)>
<!ATTLIST consultations
  xmlns CDATA #FIXED ''>

<!ELEMENT surgeries (#PCDATA)>
<!ATTLIST surgeries
  xmlns CDATA #FIXED ''>

<!ELEMENT LaborarotyTestResults (#PCDATA)>
<!ATTLIST LaborarotyTestResults
  xmlns CDATA #FIXED ''>

<!ELEMENT Bank (#PCDATA)>
<!ATTLIST Bank
  xmlns CDATA #FIXED ''>

<!ELEMENT AccountId (#PCDATA)>
<!ATTLIST AccountId
  xmlns CDATA #FIXED ''>

<!ELEMENT transaction (transactionId,date,amountDebit,reason)>
<!ATTLIST transaction
  xmlns CDATA #FIXED ''>

<!ELEMENT check (date,health,medicine)>
<!ATTLIST check
  xmlns CDATA #FIXED ''>

<!ELEMENT transactionId (#PCDATA)>
<!ATTLIST transactionId
  xmlns CDATA #FIXED ''>

<!ELEMENT amountDebit (#PCDATA)>
<!ATTLIST amountDebit
  xmlns CDATA #FIXED ''>

<!ELEMENT reason (#PCDATA)>
<!ATTLIST reason
  xmlns CDATA #FIXED ''>

<!ELEMENT health (#PCDATA)>
<!ATTLIST health
  xmlns CDATA #FIXED ''>

<!ELEMENT medicine (#PCDATA)>
<!ATTLIST medicine
  xmlns CDATA #FIXED ''>

<!ELEMENT address (#PCDATA)>
<!ATTLIST address
  xmlns CDATA #FIXED ''>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date
  xmlns CDATA #FIXED ''>

=== DeepuBhasin/Personalprojects/7. XML/robertogarciaga-attachments/xml_file.xml
<?xml version="1.0" standalone="no"?>
<!-- <?xml-stylesheet type="text/xsl" href="xsl/1_patient_insurance.xsl"?> -->
<!-- <?xml-stylesheet type="text/xsl" href="xsl/2_patient_physician.xsl"?> -->
<?xml-stylesheet type="text/xsl" href="xsl/3_patient.xsl"?>
<!DOCTYPE data SYSTEM "xml_schema.dtd">
<data>
	<electricalMedicalRecord>
		<patientInfromation>
			<personalInfromation>
				<userId>PPAA11</userId>
				<FirstName>Wisdom</FirstName>
			 	<lastName>Witherspoon</lastName>
			 	<gender>Male</gender>
			 	<address>Ronda de Sant Pere, 35, 08010 Barcelona, Spain</address>
				<age>25</age>
			 	<weight>90 kg</weight>
			</personalInfromation>
			<MedicalInfromation>
				<TreatmentOf>Skin</TreatmentOf>
				<subCategory>Acne types</subCategory>
				<medication>Antibacterials</medication>
				<allergies>Irritation on Skin</allergies>
				<immunizationStatus>Qualitative Immunoblot</immunizationStatus>
				<medicalHistory>
					<consultations>5</consultations>
					<surgeries>5</surgeries>
					<LaborarotyTestResults>High level of protines in blood.High level of irons, Low levels of glucose</LaborarotyTestResults>
				</medicalHistory>
				<billingInfromation>
					<Bank>Goldman Sachs</Bank>
					<AccountId>ES125098537038930</AccountId>
				</billingInfromation>
			</MedicalInfromation>
		</patientInfromation>
		<patientInfromation>
		<personalInfromation>
			<userId>PPBB22</userId>
			<FirstName>Bellamy</FirstName>
		 	<lastName>Sawyer</lastName>
		 	<gender>Male</gender>
		 	<address>Av. de Portugal, 209, 03130 Santa Pola, Alicante, Spain</address>
			<age>55</age>
		 	<weight>100 kg</weight>
		</personalInfromation>
			<MedicalInfromation>
				<TreatmentOf>Heart</TreatmentOf>
				<subCategory>Aorta disease and Marfan syndrome</subCategory>
				<medication>Blood pressure low</medication>
				<allergies>Tall and slender build</allergies>
				<immunizationStatus>nearsightedness</immunizationStatus>
				<medicalHistory>
					<consultations>4</consultations>
					<surgeries>3</surgeries>
					<LaborarotyTestResults>The pressure of blood leaving your heart can cause the wall of your aorta to bulge out, like a weak spot in a tire.</LaborarotyTestResults>
				</medicalHistory>
				<billingInfromation>
					<Bank>Bankinter</Bank>
					<AccountId>BSI18537038964730</AccountId>
				</billingInfromation>
			</MedicalInfromation>
		</patientInfromation>
		<patientInfromation>
		<personalInfromation>
				<userId>PPCC33</userId>
				<FirstName>MacConnell</FirstName>
			 	<lastName>Selina</lastName>
			 	<gender>Female</gender>
			 	<address>Paseo del Mediterráneo, 363, 04638 Mojácar, Almería, Spain</address>
				<age>40</age>
			 	<weight>60 kg</weight>
			</personalInfromation>
			<MedicalInfromation>
				<TreatmentOf>Eyes</TreatmentOf>
				<subCategory>Glaucoma</subCategory>
				<medication>Carbonic anhydrase inhibitors (CAIs) </medication>
				<allergies>Prostaglandin Analogs</allergies>
				<immunizationStatus>Neurodegeneration and Neuroprotection</immunizationStatus>
				<medicalHistory>
					<consultations>4</consultations>
					<surgeries>2</surgeries>
					<LaborarotyTestResults>The range for normal pressure is 12-22 mm Hg (“mm Hg” refers to millimeters of mercury, a scale used to record eye pressure).</LaborarotyTestResults>
				</medicalHistory>
				<billingInfromation>
					<Bank>KutxaBank</Bank>
					<AccountId>KBYDI18537038930</AccountId>
				</billingInfromation>
			</MedicalInfromation>
		</patientInfromation>
		<patientInfromation>
			<personalInfromation>
				<userId>PPDD44</userId>
				<FirstName>Wilton</FirstName>
			 	<lastName>Starla</lastName>
			 	<gender>Female</gender>
			 	<address>Gran Via de les Corts Catalanes, 415, 08015 Barcelona, B, Spain</address>
				<age>29</age>
			 	<weight>70 kg</weight>
			</personalInfromation>
			<MedicalInfromation>
				<TreatmentOf>Brain</TreatmentOf>
				<subCategory>Brain Tumor</subCategory>
				<medication>chemotherapy</medication>
				<allergies>brain cancer</allergies>
				<immunizationStatus>DCVax-L</immunizationStatus>
				<medicalHistory>
					<consultations>3</consultations>
					<surgeries>2</surgeries>
					<LaborarotyTestResults>The most common imaging tests for brain tumors are magnetic resonance imaging (MRI) and computed tomography (CAT scan, CT scan). </LaborarotyTestResults>
				</medicalHistory>
				<billingInfromation>
					<Bank>Caja Rural Group</Bank>
					<AccountId>CRGI1464780802526</AccountId>
				</billingInfromation>
			</MedicalInfromation>
		</patientInfromation>
		<patientInfromation>
		<personalInfromation>
			<userId>PPEE55</userId>
			<FirstName>Lyon</FirstName>
		 	<lastName>Laz</lastName>
		 	<gender>Male</gender>
		 	<address>Calle de Zurbano, 8, 28010 Madrid, Spain</address>
			<age>35</age>
		 	<weight>95 kg</weight>
		</personalInfromation>
		<MedicalInfromation>
			<TreatmentOf>Cancer</TreatmentOf>
			<subCategory>Chest Cancer</subCategory>
			<medication>Abemaciclib </medication>
			<allergies>asthma</allergies>
			<immunizationStatus>NeuVax</immunizationStatus>
			<medicalHistory>
				<consultations>4</consultations>
				<surgeries>3</surgeries>
				<LaborarotyTestResults>A hormone receptor is a specialized protein located on the surface of or within a cell.</LaborarotyTestResults>
			</medicalHistory>
			<billingInfromation>
				<Bank>Bankia</Bank>
				<AccountId>BED144785508026</AccountId>
			</billingInfromation>
		</MedicalInfromation>
	</patientInfromation>
	</electricalMedicalRecord>
	<insuranceComapny>
		<company>
			<companyId>CCBB11</companyId>
			<companyName>MAPFRE</companyName>
			<location>Spain, Madrid, Majadahonda</location>
			<revenue>$33.6B</revenue>
			<employees>34.3K</employees>
			<customerDetails>
				<customerId userId="PPAA11">PPAA11</customerId>	
				<totalBalance currency="usd">5210$</totalBalance>
				<timePeriod>1 year</timePeriod>
				<transactions>
					<transaction>
						<transactionId>t12wwew3324tfkuosoiklsih11</transactionId>
						<date>1-04-2020</date>
						<amountDebit>50$</amountDebit>
						<reason>Treatment For Skin</reason>
					</transaction>
					<transaction>
						<transactionId>43564655rtt2627bd</transactionId>
						<date>2-04-2020</date>
						<amountDebit>70$</amountDebit>
						<reason>Treatment For Arm skin</reason>
					</transaction>	
					<transaction>
						<transactionId>t3727620djt2627bd</transactionId>
						<date>3-04-2020</date>
						<amountDebit>60$</amountDebit>
						<reason>Treatment For Hand skin</reason>
					</transaction>
					<transaction>
						<transactionId>394989d27bddi09eeheio</transactionId>
						<date>4-04-2020</date>
						<amountDebit>160$</amountDebit>
						<reason>Treatment For leg skin</reason>
					</transaction>
					<transaction>
						<transactionId>3u09ejijd27bddi0siee098978</transactionId>
						<date>5-04-2020</date>
						<amountDebit>160$</amountDebit>
						<reason>Treatment For neck skin</reason>
					</transaction>
				</transactions>
			</customerDetails>
		</company>
		<company>
			<companyId>CCCC11</companyId>
			<companyName>Seguros Ocaso</companyName>
			<location>Spain, Madrid, Madrid</location>
			<revenue>$267.1M</revenue>
			<employees>30K</employees>
			<customerDetails>
				<customerId userId="PPBB22">PPBB22</customerId>	
				<totalBalance currency="usd">4500$</totalBalance>
				<timePeriod>2 year</timePeriod>
				<transactions>
					<transaction>
						<transactionId>32444rdjkdhiube</transactionId>
						<date>3-02-2020</date>
						<amountDebit>50$</amountDebit>
						<reason>Check up For Heart</reason>
					</transaction>
					<transaction>
						<transactionId>i4r3wr4rudhdihdi092029</transactionId>
						<date>10-02-2020</date>
						<amountDebit>60$</amountDebit>
						<reason>Check up for heart</reason>
					</transaction>
					<transaction>
						<transactionId>7687u67utw67nxbxjk</transactionId>
						<date>11-04-2020</date>
						<amountDebit>20$</amountDebit>
						<reason>Check of For heart pump</reason>
					</transaction>
				</transactions>
			</customerDetails>
		</company>
		<company>
			<companyId>CCDD33</companyId>
			<companyName>SANITAS</companyName>
			<location>Spain, Madrid, Madrid</location>
			<revenue>$1.6B</revenue>
			<employees>11K</employees>
			<customerDetails>
				<customerId userId="PPCC33">PPCC33</customerId>	
				<totalBalance currency="usd">4554$</totalBalance>
				<timePeriod>3 year</timePeriod>
				<transactions>
					<transaction>
						<transactionId>4987498fjj095059123trt</transactionId>
						<date>8-08-2020</date>
						<amountDebit>520$</amountDebit>
						<reason>Eyes Operation</reason>
					</transaction>
					<transaction>
						<transactionId>48230940930oifhiubiuvuev</transactionId>
						<date>18-08-2020</date>
						<amountDebit>200$</amountDebit>
						<reason>Check of For Eyes</reason>
					</transaction>
				</transactions>
			</customerDetails>
		</company>
		<company>
			<companyId>CCEE44</companyId>
			<companyName>logo for Grupo Catalana Occidente Grupo Catalana Occidente</companyName>
			<location>Spain, Catalonia, Sant Cugat del Valles</location>
			<revenue>$375M</revenue>
			<employees>6.5K</employees>
			<customerDetails>
				<customerId userId="PPDD44">PPDD44</customerId>	
				<totalBalance currency="usd">48425$</totalBalance>
				<timePeriod>9 year</timePeriod>
				<transactions>
					<transaction>
						<transactionId>ueute7726828</transactionId>
						<date>8-02-2020</date>
						<amountDebit>1520$</amountDebit>
						<reason>Brain Operation</reason>
					</transaction>
					<transaction>
						<transactionId>37653gssbklsm</transactionId>
						<date>18-02-2020</date>
						<amountDebit>2000$</amountDebit>
						<reason>Brain Operation</reason>
					</transaction>
				</transactions>
			</customerDetails>
		</company>
		<company>
			<companyId>PPEE55</companyId>
			<companyName>SegurCaixa Adeslas</companyName>
			<location>Spain, Madrid, Madrid</location>
			<revenue>$4.7B</revenue>
			<employees>6.1K</employees>
			<customerDetails>
